### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by gregorwolf** [gregorwolf/SAP-NPM-API-collection#1]
Hi @Seeker0,
thank you for this great repository as SAP seems not to be able to publish anything in a human readable format. But your repository get's quite outdated. Could you either update it or describe the steps on how you've built it?
Best regards
Gregor

**Comment by Seeker0** [comment]
Hey Gregor. Sorry for the delay in getting back to you. Honestly, I was surprised to hear from you. I built this repo to help myself with something I was working on for a client. Didn't really expect anyone else to use it. Shortly after that, the client decided against me using SAP NPM packages and/or open sourced NPM packages, so the repo was forgotten. If you're interested in continuing to work on it, I'm down.
